# Sidebar navigation

- label: 'Home Page'
  link: '/'
- label: 'My Roadmap'
  link: '/roadmap'

- label: ğŸ“ Useful
  items:
    - label: 'Links'
      link: '/link/links'
    - label: 'Tools'
      link: '/link/tools'

- label: â­• Resources for
  items:
    - label: 'HTML & CSS'
      link: '/learning/html-css'
    - label: 'JavaScript \ React '
      link: '/learning/javascript-react'
    - label: 'TypeScript'
      link: '/learning/typescript'
    - label: 'Node JS'
      link: '/learning/nodejs'
    - label: 'MongoDB'
      link: '/learning/mongodb'

- label: âœ‰ï¸ More
  items:
    - label: Contact
      link: /contact

