# Sidebar navigation

- label: 'About me'
  link: '/'
- label: 'Roadmap'
  link: '/roadmap'
- label: 'Now'
  link: '/now'
- label: 'Uses'
  link: '/uses'



- label:  ğŸ”—Links
  items:
    - label: 'Github'
      link: https://github.com/Ted2xmen
    - label: 'Medium'
      link: https://ted2xmen.medium.com/
    - label: 'CodePen'
      link: https://codepen.io/ted2xmen
    - label: 'Linkedin'
      link: https://www.linkedin.com/in/tugrulerdemdogru/
    - label: 'Twitter'
      link: https://twitter.com/ted2xmen


- label:  â‡ï¸Projects
  items:
    - label: 'New Poems'
      link: https://ted2xmen.github.io/random-ozel/
    - label: 'Vue Todo App'
      link: https://ted2xmen.github.io/Vue-Todo-App/
    - label: 'Searchon'
      link: https://searchon.vercel.app/
    - label: 'Patika Projects'
      link: https://ted2xmen.github.io/Projects/
    - label: 'Kutuphaneden'
      link: https://ted2xmen.github.io/kutuphaneden/
    - label: 'Arastirmanv5'
      link: https://arastirmanv4.vercel.app/

