# Sidebar navigation

- label: 'Home Page'
  link: '/'
- label: 'Status'
  link: '/status'

- label: ğŸ“ Useful
  items:
    - label: 'Links'
      link: '/links/links'
    - label: 'Tools'
      link: '/links/tools'
    - label: 'Libraries'
      link: '/links/libraries'

- label: ğŸ“ Resources for
  items:
    - label: 'UI & UX'
      link: '/learning/design'
    - label: 'HTML and CSS'
      link: '/learning/html-css'
    - label: 'JavaScript'
      link: '/learning/javascript'
    - label: 'React'
      link: '/learning/react'
    - label: 'TypeScript'
      link: '/learning/typescript'
    - label: 'Node JS'
      link: '/learning/nodejs'
    - label: 'MongoDB'
      link: '/learning/mongodb'

- label: âœ‰ï¸ More
  items:
    - label: Contact
      link: /contact

