# Sidebar navigation

- label: 'About me'
  link: '/'
- label: 'Roadmap'
  link: '/roadmap'


- label: ğŸŸ¨ JS Notes
  items:
    - label: 'Functions'
      link: '/notes/functions'
    - label: 'Loops and Iteration'
      link: '/notes/loops-and-iteration'
    - label: 'Map - Reduce - Filter'
      link: '/notes/map-reduce-filter'

- label:  Useful
  items:
    - label: 'ğŸ”—Links and Tools'
      link: '/link/links-and-tools'
    - label: 'â‡ï¸Commands'
      link: '/link/commands'
    - label: 'â­•Crash Courses'
      link: '/link/crash-courses'


- label: âœ‰ï¸ More
  items:
    - label: Contact
      link: /contact

