# Sidebar navigation

- label: 'Home Page'
  link: '/'
- label: 'Roadmap'
  link: '/roadmap'

- label: ğŸ“ Useful Links
  items:
    - label: 'Tools'
      link: '/front/tools'
    - label: 'Libraries'
      link: '/front/libraries'
    - label: 'Design 101'
      link: '/front/design'

- label: ğŸ“ Resources for
  items:
    - label: 'HTML and CSS'
      link: '/learning/html-css'
    - label: 'JavaScript'
      link: '/learning/javascript'
    - label: 'React'
      link: '/learning/react'
    - label: 'TypeScript'
      link: '/learning/typescript'
    - label: 'Node JS'
      link: '/learning/nodejs'
    - label: 'MongoDB'
      link: '/learning/mongodb'

- label: âœ‰ï¸ More
  items:
    - label: Contact
      link: /contact

